{{- if and (eq .Values.loki.singleBinary.persistence.storageClass "manual") .Values.loki.singleBinary.persistence.enabled }}
{{- range $index, $end := until (.Values.loki.singleBinary.replicas | int) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-volume-{{ $index }}
  labels:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-loki-{{ $index }}
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: {{ $.Values.loki.singleBinary.persistence.reclaimPolicy | default "Retain" }}
  capacity:
    storage: {{ $.Values.loki.singleBinary.persistence.size }}
  accessModes:
    {{- range $.Values.loki.singleBinary.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  hostPath:
    path: "/var/local/{{ $.Release.Name }}/loki/pod-{{ $index }}"
---
{{- end }}
{{- end }}
