{{- if and (eq .Values.loki.minio.persistence.storageClass "manual") .Values.loki.minio.persistence.enabled }}
{{- range $index, $end := until (.Values.loki.minio.replicas | int) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-{{ $index }}
  labels:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-minio-{{ $index }}
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: {{ $.Values.loki.minio.persistence.reclaimPolicy | default "Retain" }}
  capacity:
    storage: {{ $.Values.loki.minio.persistence.size }}
  accessModes:
    - {{ $.Values.loki.minio.persistence.accessMode }}
  hostPath:
    path: "/var/local/{{ $.Release.Name }}/minio/pod-{{ $index }}"
---
{{- end }}
{{- end }}
