name: Release Charts
on:
  push:
    branches:
      - develop
      - "release/**"
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: cachix/install-nix-action@v31.3.0
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell --pure --run "echo" ./scripts/staging/shell.nix

      - name: Validate if the chart release is allowed
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            TRIGGER_TYPE="develop"
          else
            TRIGGER_TYPE="prerelease"
          fi

          nix-shell --pure --run "./scripts/staging/validate.sh \
            --trigger ${TRIGGER_TYPE}" ./scripts/staging/shell.nix

      - name: Publish openebs develop or prerelease umbrella helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        env:
          TMPDIR: /tmp
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
