name: Release Charts
on:
  push:
    paths:
      - 'charts/**'
    branches:
      - develop
      - "release/**"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_version.outputs.skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Block publish if version is a develop pre-release
        id: check_version
        run: |
          VERSION=$(yq '.version' charts/Chart.yaml)
          if [[ "$VERSION" == *-develop* ]]; then
            echo "Chart version is a develop prerelease: $VERSION"
            echo "Skipping Publish"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish openebs develop or prerelease umbrella helm chart
        if: steps.check_version.outputs.skip != 'true'
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
