name: Release Charts
on:
  push:
    branches:
      - develop
      - "release/**"
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_version.outputs.skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Block publish if version is a develop pre-release
        id: check_version
        run: |
          VERSION=$(yq '.version' charts/Chart.yaml)
          BRANCH="${GITHUB_REF#refs/heads/}"

          if [[ ! "$VERSION" =~ -(prerelease|develop)$ ]]; then
            echo "Version doesn't end with -prerelease or -develop: $VERSION"
            echo "Skipping Publish"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          elif [[ "$BRANCH" == release/* && "$VERSION" =~ -develop$ ]]; then
            echo "Release branch cannot have -develop version"
            echo "Branch: $BRANCH, Version: $VERSION"
            echo "Skipping Publish"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          elif [[ "$BRANCH" == "develop" && "$VERSION" =~ -prerelease$ ]]; then
            echo "Develop branch cannot have -prerelease version"
            echo "Branch: $BRANCH, Version: $VERSION"
            echo "Skipping Publish"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "Version and branch combination valid"
            echo "Branch: $BRANCH, Version: $VERSION"
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish openebs develop or prerelease umbrella helm chart
        if: steps.check_version.outputs.skip != 'true'
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
