name: Nightly Update
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nightly-update-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - develop
      fail-fast: false
    steps:
      - name: Awaiting
        id: dispatch
        uses: the-actions-org/workflow-dispatch@v4
        with:
          token: ${{ secrets.ORG_CI_GITHUB }}
          ref: ${{ matrix.branch }}
          workflow: mod-update.yml
          wait-for-completion: true
          wait-for-completion-timeout: 4h
          display-workflow-run-url-timeout: 1h
      - name: Print Status
        if: always()
        run: |
          echo "Workflow for branch ${{ matrix.branch }} completed with status: ${{ steps.dispatch.outputs.workflow-conclusion }}"
          echo "For more details, see ${{ steps.dispatch.outputs.workflow-url }}"
