name: Build image
on:
  pull_request:
    branches:
      - develop
      - 'release/**'
jobs:
  plugin-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            rust:
              - 'plugin/**'
              - 'nix/**'
              - shell.nix
              - default.nix
              - Cargo.toml
              - Cargo.lock
              - 'mayastor/**'
      - uses: DeterminateSystems/nix-installer-action@v14
        if: steps.changes.outputs.rust == 'true'
      - uses: DeterminateSystems/magic-nix-cache-action@v8
        if: steps.changes.outputs.rust == 'true'
      - name: Test building the static binaries
        if: steps.changes.outputs.rust == 'true'
        run: nix-build -A utils.debug.x86_64.linux-musl.kubectl-openebs --arg incremental false

