name: Publish To Krew Index
on:
  release:
    types: [ published ]
jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: latest-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LATEST_VERSION=$(gh api repos/${{ github.repository_owner }}/openebs/releases/latest | jq -r '.tag_name')
          echo "Latest published version:$LATEST_VERSION"
          echo "latestTag=$LATEST_VERSION" >> "$GITHUB_OUTPUT"
      - name: Update krew index
        if: ${{ !github.event.release.prerelease && (steps.latest-release.outputs.latestTag == github.event.release.tag_name) }}
        uses: rajatjindal/krew-release-bot@v0.0.47
