name: Release Artifacts
on:
  push:
    branches:
      - 'release/**'
      - 'develop'
  workflow_call:
    inputs:
      tag:
        description: 'Tag to build, example: v4.2.0'
        required: true
        type: string

jobs:
  kubectl-plugin:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          # NOTE: Update the .krew.yaml file (if required) when making changes here.
          - os: oracle-vm-8cpu-32gb-x86-64
            target: linux-musl
            arch: x86_64
          - os: oracle-vm-8cpu-32gb-x86-64
            target: linux-musl
            arch: aarch64
          - os: macos-14
            target: apple-darwin
            arch: aarch64
          - os: macos-14
            target: apple-darwin
            arch: x86_64
            platform: x86_64-darwin
          - os: oracle-vm-8cpu-32gb-x86-64
            target: windows-gnu
            arch: x86_64
            suffix: .exe

    steps:
      - uses: actions/checkout@v4
        env:
          checkout_token: ${{ secrets.ORG_CI_GITHUB }}
        if: ${{ env.checkout_token == '' }}
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/checkout@v4
        env:
          checkout_token: ${{ secrets.ORG_CI_GITHUB }}
        if: ${{ env.checkout_token != '' }}
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.ORG_CI_GITHUB }}

      - uses: cachix/install-nix-action@v31.3.0
        with:
          enable_kvm: false
      - run: |
          TAG_ARG=""
          SYSTEM_ARG=""
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG_ARG="--argstr tag ${{ inputs.tag }}"
          fi
          if [[ -n "${{ matrix.platform }}" ]]; then
            SYSTEM_ARG="--argstr system ${{ matrix.platform }}"
          fi
          nix-build -A utils.release.${{ matrix.arch }}.${{ matrix.target }}.kubectl-openebs --arg incremental false $TAG_ARG $SYSTEM_ARG

      - name: Archive executable
        run: |
          tar -czvf kubectl-openebs-${{ matrix.arch }}-${{ matrix.target }}.tar.gz LICENSE -C result/bin kubectl-openebs${{ matrix.suffix }}

      - uses: actions/upload-artifact@v4
        with:
          name: kubectl-openebs-${{ matrix.arch }}-${{ matrix.target }}
          path: kubectl-openebs-${{ matrix.arch }}-${{ matrix.target }}.tar.gz
          if-no-files-found: error

