name: Publish chart upon release creation

on:
  release:
    types:
      - "published"

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          submodules: recursive

      - uses: cachix/install-nix-action@v31.3.0
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell --pure --run "echo" ./shell.nix

      - name: Remove prerelease label from dependencies
        run: |
          nix-shell --pure --run "./scripts/helm/update-version-upon-release.sh" ./shell.nix

      - name: Publish openebs umbrella helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        env:
          TMPDIR: /tmp
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
